apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapp-frontend
  namespace: taskapp
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: taskapp-frontend
  template:
    metadata:
      labels:
        app: taskapp-frontend
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: taskapp-frontend
      containers:
      - name: frontend
        image: ghcr.io/ts-a-devops/taskapp-frontend:26da2b0   # pinned tag, NOT :latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: taskapp
spec:
  selector:
    app: taskapp-frontend
  ports:
  - port: 80
    targetPort: 80
