[control_plane]
k3s-master ansible_host=16.16.213.192 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/capstone_key

[workers]
k3s-worker-1 ansible_host=13.63.160.165 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/capstone_key
k3s-worker-2 ansible_host=16.16.57.223 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/capstone_key

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
